version: '3.8'
name: mevn-stack-auth

services:
  backend:
    build: ./backend
    container_name: back-end
    ports:
      - 5000:5000
    volumes:
      - ./backend:/backend_application/app
      - /backend_application/node_modules
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    container_name: front-end
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend_application
      - /frontend_application/node_modules
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes: 
      - ./backend/app/db/mongo-init/:/docker-entrypoint-initdb.d/:ro  
